dashboard/urls.py
from django.urls import path
from dashboard import views


urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('analyse/', views.analyse, name='analyse'),
    path('search/', views.search, name='search'),
    path('bet/', views.bet, name='bet'),
    path('bet/refresh', views.bet_refresh, name='bet-refresh')
]

maxbet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard'))
]

dashboard/models.py
from django.db import models


class BetMatch(models.Model):

    SIDE_CHOICES = (
        ('1', 'Home'),
        ('N', 'Draw'),
        ('2', 'Away')
    )

    summary = models.CharField(max_length=200, primary_key=True)
    side = models.CharField(max_length=1, choices=SIDE_CHOICES)
    website = models.CharField(max_length=100)
    odd = models.FloatField()
    bet_fraction = models.FloatField()
    match_datetime = models.DateTimeField()

    def __str__(self):
        return self.summary


class RefreshTime(models.Model):

    TYPE_CHOICES = (
        ('bet', 'bet'),
        ('ana', 'analyse')
    )

    type = models.CharField(max_length=3, choices=TYPE_CHOICES, primary_key=True)
    refresh_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.refresh_datetime

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

from .models import BetMatch, RefreshTime
from core.analysis import db
from core.analysis.simulation import Simulation, ValueBetSimulation
from core.common import distribution

WEBSITES = ['William Hill', 'Marathon Bet', 'Boyle Sports', 'Betway', 'BetBright', '10Bet', 'SportPesa',
            'Sport Nation', 'Smarkets', 'Coral', 'Sportingbet', 'Royal Panda']
# WEBSITES = ['Betway', 'William Hill', 'Sportingbet', 'Coral', 'Betdaq']

RESOLUTION = 0.01


def index(request):
    return render(request, 'dashboard/index.html')


def register(request):
    raise Http404


def analyse(request):
    match_data = db.get_finished_match_data()
    params = {Simulation.BET_ODD_POWER: 2., Simulation.BET_RETURN_POWER: 0., Simulation.MIN_PROB: 0.25,
              Simulation.MIN_RETURN: 1., Simulation.MAX_RETURN: 100., Simulation.WEBSITES: WEBSITES,
              Simulation.BET_FACTOR: .5 / len(WEBSITES)}
    money = ValueBetSimulation.simulate_bets(match_data, params)
    rounded_ymin = float(int(min(money) / RESOLUTION)) * RESOLUTION
    rounded_ymax = float(int(max(money) / RESOLUTION)) * RESOLUTION
    context = {'bet_sim': list(enumerate(money)), 'ymin': rounded_ymin, 'ymax': rounded_ymax}
    return render(request, 'dashboard/analyse.html', context)


def search(request):
    raise Http404


def bet(request):
    bet_matches = sorted(BetMatch.objects.all(), key=lambda x: x.summary)
    if RefreshTime.objects.exists():
        refresh_time = RefreshTime.objects.all()[0].refresh_datetime
    else:
        refresh_time = 'Never'
    context = {'bet_matches': bet_matches, 'refresh_time': refresh_time}
    return render(request, 'dashboard/bet.html', context)


def bet_refresh(request):
    BetMatch.objects.all().delete()
    matches = db.get_future_match_data()
    params = {Simulation.BET_ODD_POWER: 2., Simulation.BET_RETURN_POWER: 0., Simulation.MIN_PROB: 0.3,
              Simulation.MIN_RETURN: 1.05, Simulation.MAX_RETURN: 100., Simulation.WEBSITES: WEBSITES}
    bet_matches = distribution.get_value_bets(params, matches)
    for summary, side_id, website, odd, match_datetime, bet_fraction in bet_matches:
        bet_match = BetMatch(summary=summary, side=side_id, website=website, odd=odd,
                             bet_fraction=bet_fraction, match_datetime=match_datetime)
        bet_match.save()
    RefreshTime.objects.filter(type='bet').delete()
    RefreshTime(type='bet').save()
    return redirect('dashboard:bet')

dashboard/templates/dashboard/analyse.html
{% extends 'dashboard/base.html' %}

{% block content %}

{% load static %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Analysis</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Simulation of invested money
            </div>
            <div class="panel-body">
                <div id="bet-simulation"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MaxBet - Bet efficiently</title>

    {% load static %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'dashboard/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'dashboard/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'dashboard/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'dashboard/css/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'dashboard/css/font-awesome.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'dashboard:index' %}">MaxBet</a>
            </div>
            <!-- /.navbar-header -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="{% url 'dashboard:index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:register' %}"><i class="fa fa-table fa-fw"></i> Register</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:analyse' %}"><i class="fa fa-bar-chart-o fa-fw"></i> Analyse</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:bet' %}"><i class="fa fa-play-circle fa-fw"></i> Bet</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
        {% block content %}{% endblock %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'dashboard/js/metisMenu.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'dashboard/js/raphael.min.js' %}"></script>
    <script src="{% static 'dashboard/js/morris.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dashboard/js/sb-admin-2.js' %}"></script>

    <!-- Dynamic diagrams -->
    <script>
        $(function() {
            new Morris.Line({
                element: 'bet-simulation',
                data: [
                    {% for index, money in bet_sim %}
                        { index: {{ index }}, money: {{ money }} },
                    {% endfor %}
                ],
                xkey: 'index',
                ykeys: ['money'],
                labels: ['Money'],
                pointSize: 0,
                parseTime: false,
                ymin: {{ymin}},
                ymax: {{ymax}}
            });
        });
    </script>
</body>

</html>

dashboard/templates/dashboard/bet.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Bets</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <a href="{% url 'dashboard:bet-refresh' %}"><i class="fa fa-refresh fa-fw"></i> Refresh</a>
        <br/>
        <em>Last refreshed: {{ refresh_time }}</em>
        <br/>
        <br/>
        <p>Number of bet matches: {{ bet_matches|length }}</p>
        <hr/>
    </div>
</div>

<div class="row">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>Match</th>
                <th>Side</th>
                <th>Website</th>
                <th>Odd</th>
                <th>Bet fraction</th>
            </tr>
        </thead>
        <tbody>
{% for bet_match in bet_matches %}
            <tr class="odd gradeX">
                <td>{{ bet_match.summary }}</td>
                <td>{{ bet_match.side }}</td>
                <td>{{ bet_match.website }}</td>
                <td class="center">{{ bet_match.odd }}</td>
                <td class="center">{{ bet_match.bet_fraction }}</td>
            </tr>
{% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}